import { createTheme, createThemeContract, createGlobalTheme, globalStyle, assignVars } from '@vanilla-extract/css'
import * as radixColors from '@radix-ui/colors'

// Define theme contract (variable names)
export const vars = createThemeContract({
  color: {
    // Radix color scales - gray
    gray1: null, gray2: null, gray3: null, gray4: null, gray5: null,
    gray6: null, gray7: null, gray8: null, gray9: null, gray10: null,
    gray11: null, gray12: null,

    // blue
    blue1: null, blue2: null, blue3: null, blue4: null, blue5: null,
    blue6: null, blue7: null, blue8: null, blue9: null, blue10: null,
    blue11: null, blue12: null,

    // crimson
    crimson1: null, crimson2: null, crimson3: null, crimson4: null, crimson5: null,
    crimson6: null, crimson7: null, crimson8: null, crimson9: null, crimson10: null,
    crimson11: null, crimson12: null,

    // grass
    grass1: null, grass2: null, grass3: null, grass4: null, grass5: null,
    grass6: null, grass7: null, grass8: null, grass9: null, grass10: null,
    grass11: null, grass12: null,

    // slate
    slate1: null, slate2: null, slate3: null, slate4: null, slate5: null,
    slate6: null, slate7: null, slate8: null, slate9: null, slate10: null,
    slate11: null, slate12: null,

    // mauve
    mauve1: null, mauve2: null, mauve3: null, mauve4: null, mauve5: null,
    mauve6: null, mauve7: null, mauve8: null, mauve9: null, mauve10: null,
    mauve11: null, mauve12: null,

    // mauveA
    mauveA1: null, mauveA2: null, mauveA3: null, mauveA4: null, mauveA5: null,
    mauveA6: null, mauveA7: null, mauveA8: null, mauveA9: null, mauveA10: null,
    mauveA11: null, mauveA12: null,

    // amber
    amber1: null, amber2: null, amber3: null, amber4: null, amber5: null,
    amber6: null, amber7: null, amber8: null, amber9: null, amber10: null,
    amber11: null, amber12: null,

    // purple
    purple1: null, purple2: null, purple3: null, purple4: null, purple5: null,
    purple6: null, purple7: null, purple8: null, purple9: null, purple10: null,
    purple11: null, purple12: null,

    // green
    green1: null, green2: null, green3: null, green4: null, green5: null,
    green6: null, green7: null, green8: null, green9: null, green10: null,
    green11: null, green12: null,

    // red
    red1: null, red2: null, red3: null, red4: null, red5: null,
    red6: null, red7: null, red8: null, red9: null, red10: null,
    red11: null, red12: null,

    // Semantic colors
    accent: null,
    background: null,
    backgroundAlt: null,
    backgroundOverlay: null,
    text: null,
    textMuted: null,
    error: null,
    warning: null,
    success: null,
    white: null,
    black: null,
    deep: null,
  },
  font: {
    body: null,
    heading: null,
    monospace: null,
  },
  fontSize: {
    xs: null, sm: null, md: null, lg: null, xl: null,
    '2xl': null, '3xl': null, '4xl': null, '5xl': null,
    '6xl': null, '7xl': null, '8xl': null, '9xl': null,
    default: null,
  },
  space: {
    px: null, '0_5': null, '1': null, '1_5': null, '2': null,
    '2_5': null, '3': null, '3_5': null, '4': null, '5': null,
    '6': null, '7': null, '8': null, '9': null, '10': null,
    '12': null, '14': null, '16': null, '20': null, '24': null,
    '28': null, '32': null, '36': null, '40': null, '44': null,
    '48': null, '52': null, '56': null, '60': null, '64': null,
    '72': null, '80': null, '96': null,
  },
  radius: {
    none: null, sm: null, base: null, md: null, lg: null,
    xl: null, '2xl': null, '3xl': null, full: null,
  },
  fontWeight: {
    body: null,
    heading: null,
    bold: null,
  },
  lineHeight: {
    one: null,
    body: null,
    heading: null,
  },
})

// Light theme
export const lightTheme = createTheme(vars, {
  color: {
    ...radixColors.gray,
    ...radixColors.blue,
    ...radixColors.crimson,
    ...radixColors.grass,
    ...radixColors.slate,
    ...radixColors.mauve,
    ...radixColors.mauveA,
    ...radixColors.amber,
    ...radixColors.purple,
    ...radixColors.green,
    ...radixColors.red,
    accent: '#9D2DFF',
    background: radixColors.gray.gray1,
    backgroundAlt: radixColors.gray.gray4,
    backgroundOverlay: radixColors.mauve.mauve2,
    text: radixColors.gray.gray12,
    textMuted: radixColors.gray.gray10,
    error: radixColors.red.red9,
    warning: radixColors.amber.amber11,
    success: radixColors.grass.grass11,
    white: 'white',
    black: 'black',
    deep: 'rgb(244, 244, 244)',
  },
  font: {
    body: 'Work Sans, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    heading: 'Work Sans, sans-serif',
    monospace: 'Roboto Mono, monospace',
  },
  fontSize: {
    xs: '0.6875rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '4.5rem',
    '8xl': '6rem',
    '9xl': '8rem',
    default: '1rem',
  },
  space: {
    px: '1px',
    '0_5': '0.125rem',
    '1': '0.25rem',
    '1_5': '0.375rem',
    '2': '0.5rem',
    '2_5': '0.625rem',
    '3': '0.75rem',
    '3_5': '0.875rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '7': '1.75rem',
    '8': '2rem',
    '9': '2.25rem',
    '10': '2.5rem',
    '12': '3rem',
    '14': '3.5rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '28': '7rem',
    '32': '8rem',
    '36': '9rem',
    '40': '10rem',
    '44': '11rem',
    '48': '12rem',
    '52': '13rem',
    '56': '14rem',
    '60': '15rem',
    '64': '16rem',
    '72': '18rem',
    '80': '20rem',
    '96': '24rem',
  },
  radius: {
    none: '0',
    sm: '0.2rem',
    base: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    full: '9999px',
  },
  fontWeight: {
    body: '400',
    heading: '700',
    bold: '700',
  },
  lineHeight: {
    one: '1',
    body: '1.5',
    heading: '0.85',
  },
})

// Dark theme
export const darkTheme = createTheme(vars, {
  color: {
    ...radixColors.grayDark,
    ...radixColors.blueDark,
    ...radixColors.crimsonDark,
    ...radixColors.grassDark,
    ...radixColors.slateDark,
    ...radixColors.mauveDark,
    ...radixColors.mauveDarkA,
    ...radixColors.amberDark,
    ...radixColors.purpleDark,
    ...radixColors.greenDark,
    ...radixColors.redDark,
    accent: '#9D2DFF',
    background: radixColors.grayDark.gray1,
    backgroundAlt: radixColors.grayDark.gray4,
    backgroundOverlay: radixColors.mauveDark.mauve5,
    text: radixColors.grayDark.gray12,
    textMuted: radixColors.grayDark.gray10,
    error: radixColors.redDark.red9,
    warning: radixColors.amberDark.amber11,
    success: radixColors.grassDark.grass11,
    white: 'white',
    black: 'black',
    deep: 'rgb(10, 10, 10)',
  },
  font: {
    body: 'Work Sans, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    heading: 'Work Sans, sans-serif',
    monospace: 'Roboto Mono, monospace',
  },
  fontSize: {
    xs: '0.6875rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '4.5rem',
    '8xl': '6rem',
    '9xl': '8rem',
    default: '1rem',
  },
  space: {
    px: '1px',
    '0_5': '0.125rem',
    '1': '0.25rem',
    '1_5': '0.375rem',
    '2': '0.5rem',
    '2_5': '0.625rem',
    '3': '0.75rem',
    '3_5': '0.875rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '7': '1.75rem',
    '8': '2rem',
    '9': '2.25rem',
    '10': '2.5rem',
    '12': '3rem',
    '14': '3.5rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '28': '7rem',
    '32': '8rem',
    '36': '9rem',
    '40': '10rem',
    '44': '11rem',
    '48': '12rem',
    '52': '13rem',
    '56': '14rem',
    '60': '15rem',
    '64': '16rem',
    '72': '18rem',
    '80': '20rem',
    '96': '24rem',
  },
  radius: {
    none: '0',
    sm: '0.2rem',
    base: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    full: '9999px',
  },
  fontWeight: {
    body: '400',
    heading: '700',
    bold: '700',
  },
  lineHeight: {
    one: '1',
    body: '1.5',
    heading: '0.85',
  },
})

// Set dark theme as default on :root
createGlobalTheme(':root', vars, {
  color: {
    ...radixColors.grayDark,
    ...radixColors.blueDark,
    ...radixColors.crimsonDark,
    ...radixColors.grassDark,
    ...radixColors.slateDark,
    ...radixColors.mauveDark,
    ...radixColors.mauveDarkA,
    ...radixColors.amberDark,
    ...radixColors.purpleDark,
    ...radixColors.greenDark,
    ...radixColors.redDark,
    accent: '#9D2DFF',
    background: radixColors.grayDark.gray1,
    backgroundAlt: radixColors.grayDark.gray4,
    backgroundOverlay: radixColors.grayDark.gray2,
    text: radixColors.grayDark.gray12,
    textMuted: radixColors.grayDark.gray10,
    error: radixColors.redDark.red9,
    warning: radixColors.amberDark.amber11,
    success: radixColors.grassDark.grass11,
    white: 'white',
    black: 'black',
    deep: 'rgb(10, 10, 10)',
  },
  font: {
    body: 'Work Sans, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    heading: 'Work Sans, sans-serif',
    monospace: 'Roboto Mono, monospace',
  },
  fontSize: {
    xs: '0.6875rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '4.5rem',
    '8xl': '6rem',
    '9xl': '8rem',
    default: '1rem',
  },
  space: {
    px: '1px',
    '0_5': '0.125rem',
    '1': '0.25rem',
    '1_5': '0.375rem',
    '2': '0.5rem',
    '2_5': '0.625rem',
    '3': '0.75rem',
    '3_5': '0.875rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '7': '1.75rem',
    '8': '2rem',
    '9': '2.25rem',
    '10': '2.5rem',
    '12': '3rem',
    '14': '3.5rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '28': '7rem',
    '32': '8rem',
    '36': '9rem',
    '40': '10rem',
    '44': '11rem',
    '48': '12rem',
    '52': '13rem',
    '56': '14rem',
    '60': '15rem',
    '64': '16rem',
    '72': '18rem',
    '80': '20rem',
    '96': '24rem',
  },
  radius: {
    none: '0',
    sm: '0.2rem',
    base: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    full: '9999px',
  },
  fontWeight: {
    body: '400',
    heading: '700',
    bold: '700',
  },
  lineHeight: {
    one: '1',
    body: '1.5',
    heading: '0.85',
  },
})

// Override with light theme when .light class is present on html
globalStyle('html.light', {
  vars: assignVars(vars.color, {
    ...radixColors.gray,
    ...radixColors.blue,
    ...radixColors.crimson,
    ...radixColors.grass,
    ...radixColors.slate,
    ...radixColors.mauve,
    ...radixColors.mauveA,
    ...radixColors.amber,
    ...radixColors.purple,
    ...radixColors.green,
    ...radixColors.red,
    accent: '#9D2DFF',
    background: radixColors.gray.gray1,
    backgroundAlt: radixColors.gray.gray4,
    backgroundOverlay: radixColors.mauve.mauve2,
    text: radixColors.gray.gray12,
    textMuted: radixColors.gray.gray10,
    error: radixColors.red.red9,
    warning: radixColors.amber.amber11,
    success: radixColors.grass.grass11,
    white: 'white',
    black: 'black',
    deep: 'rgb(244, 244, 244)',
  }),
})
